---
  - name: Setup UFW for http
    ufw:
      rule: allow
      port: "80"
      state: enabled
      
  - name: Setup UFW for https
    ufw:
      rule: allow
      port: "443"
      state: enabled

  - name: Install stuff
    apt:
      name: 
        - apache2
        - php
      state: present
    notify: 
      - restart apache2
  - name: Removing default apache2 site
    file:
      name: /etc/apache2/sites-enabled/000-default.conf
      state: absent
  - name: Configuring apache2
    template:
      src: hello-ansible.conf.j2
      dest: /etc/apache2/sites-enabled/hello-ansible.conf
    notify:
      - restart apache2
  - name: Deploy code
    template:
      src: index.php.j2
      dest: /var/www/index.php
  
