---

  - hosts: all
    gather_facts: False
    tasks:
    - name: Install python
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python)

  - name: Setting up server
    become: true
    hosts: app
    roles: 
      - webserver
      - default
    vars_files:
      - vars.yml
